#!/bin/sh

bootstrap_css="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"
bootstrap_js="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"
jquery_js="//code.jquery.com/jquery-1.11.3.min.js"

python -m rst2html5                             \
    --stylesheet=$bootstrap_css                 \
    --script=$jquery_js                         \
    --script=$bootstrap_js                      \
    README.rst index.html
